<?php

test('manajemen user page is wired for super admin monitoring', function () {
    $basePath = dirname(__DIR__, 2);

    $controller = file_get_contents($basePath.'/app/Http/Controllers/Administrasi/ManajemenUserController.php');
    $userModel = file_get_contents($basePath.'/app/Models/User.php');
    $routes = file_get_contents($basePath.'/routes/web.php');
    $sidebar = file_get_contents($basePath.'/resources/views/layouts/sidebar.blade.php');
    $view = file_get_contents($basePath.'/resources/views/layouts/administrasi/manajemen-user.blade.php');

    expect($userModel)
        ->toContain('canAccessManajemenUser')
        ->toContain("'admin_snp'")
        ->toContain("'moderator_snp'")
        ->toContain('latestLog()')
        ->toContain('latestOfMany');

    expect($controller)
        ->toContain('canAccessManajemenUser')
        ->toContain('roleTypes.role')
        ->toContain('roleTypes.type')
        ->toContain('unitKerja.direktorat')
        ->toContain('Direktorat::with')
        ->toContain('latestLog')
        ->toContain("'keyword' => ['nullable', 'string', 'max:255']")
        ->toContain("'role_type_id' => ['nullable', 'integer', 'exists:tb_role_type,id']")
        ->toContain("->when(\$filters['keyword'] ?? null")
        ->toContain("->when(\$filters['role_type_id'] ?? null")
        ->toContain("->when(\$filters['direktorat_id'] ?? null")
        ->toContain("->when(\$filters['assignment'] ?? null")
        ->toContain("->oldest('created_at')")
        ->toContain("'action' => 'create_user'")
        ->toContain("'action' => 'update_user'")
        ->toContain("'assignment' => ['nullable', 'string']")
        ->toContain("'role_type_ids' => ['required', 'array', 'min:1']")
        ->toContain('resolveAssignment')
        ->toContain('authorizeRoleChanges')
        ->toContain('canManageRoleType')
        ->toContain('manageableTypeCodesForTarget')
        ->toContain('createUpdateUserRequest')
        ->toContain('createDeleteUserRequest')
        ->toContain('applyUserDelete')
        ->toContain('public function destroy')
        ->toContain('Anda tidak dapat mengedit akun yang sedang digunakan.')
        ->toContain('hasAnyAdminRole')
        ->toContain("['admin', 'moderator']")
        ->toContain("'table_name' => 'users'")
        ->toContain("'action' => 'delete_user'")
        ->toContain("'pending_admin_verification'")
        ->toContain("'pending_super_admin_approval'")
        ->toContain('$authRoleType->role?->level')
        ->toContain('> $targetLevel')
        ->toContain('$user->unitKerja()->attach($assignment')
        ->toContain('$user->komite()->attach($assignment');

    expect($routes)
        ->toContain('ManajemenUserController')
        ->toContain('/administrasi/manajemen-user')
        ->toContain("administrasi.manajemen-user.index")
        ->toContain("administrasi.manajemen-user.store")
        ->toContain("administrasi.manajemen-user.update")
        ->toContain("administrasi.manajemen-user.destroy");

    expect($sidebar)
        ->toContain('canAccessManajemenUser')
        ->toContain("route('administrasi.manajemen-user.index')")
        ->toContain('Manajemen User');

    expect($view)
        ->toContain('openCreateModal')
        ->toContain('openEditModal')
        ->toContain('openEditModalFor')
        ->toContain('Tambah User')
        ->toContain('Edit User')
        ->toContain('Daftar User')
        ->toContain('No')
        ->toContain('Email')
        ->toContain('Role')
        ->toContain('Direktorat')
        ->toContain('Unit/Komite')
        ->toContain('Aktivitas')
        ->toContain('Aksi')
        ->toContain('Terapkan Filter')
        ->toContain('Isi salah satu filter untuk mencari user tertentu.')
        ->toContain('name="keyword"')
        ->toContain('name="role_type_id"')
        ->toContain('selectedDirektoratId')
        ->toContain('assignmentOptions')
        ->toContain('name="direktorat_id"')
        ->toContain('name="assignment"')
        ->toContain('name="name"')
        ->toContain('name="email"')
        ->toContain('name="role_type_ids[]"')
        ->toContain('$authUser?->isSuperAdmin()')
        ->toContain('editAssignmentOptions')
        ->toContain('$userRoleTypes = $user->roleTypes')
        ->not->toContain('$roleTypes = $user->roleTypes')
        ->toContain('Komite tersedia di semua direktorat')
        ->toContain('User hanya dipasang ke satu unit kerja atau satu komite.')
        ->toContain('Super Admin')
        ->toContain('Admin')
        ->toContain('Moderator')
        ->toContain('PIC')
        ->toContain('Viewer')
        ->toContain("'super_admin' => '#2377b9'")
        ->toContain("'admin' => '#6bb17e'")
        ->toContain("'moderator' => '#c8e079'")
        ->toContain("'pic' => '#f59e0b'")
        ->toContain("'viewer' => '#64748b'")
        ->toContain('$user->latestLog')
        ->toContain('Simpan Perubahan')
        ->toContain('Akun Aktif')
        ->toContain('Edit')
        ->toContain("route('administrasi.manajemen-user.destroy'")
        ->toContain("@method('DELETE')")
        ->toContain('Hapus')
        ->toContain('layouts.partials.compact-pagination');
});
